project:
  type: website
  output-dir: docs

website:
  title: "Burn Carbs, Plant 1 Million Trees"
  page-footer: "Copyright 2024, Stefan Schreiber" 
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - posts.qmd
    logo: images/favicon.png
  favicon: images/favicon.png

format:
  html:
    theme: simplex
    css: styles.css
    toc: true
    page-layout: article
    email-obfuscation: javascript

editor: visual


