project:
  type: website

website:
  title: "Burn Carbs, Plant Trees!"
  page-footer: "Copyright 2024, Stefan Schreiber" 
  navbar:
    right:
      - href: index.qmd
        text: Home
      - projects.qmd
      - posts.qmd
#    logo: images/logo2.png
  favicon: images/favicon6.png

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    page-layout: full
    email-obfuscation: javascript


